# Generated by Django 3.1.3 on 2020-11-09 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fk_cliente',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Contactos.cliente'),
            preserve_default=False,
        ),
    ]
