# Generated by Django 3.1.3 on 2020-11-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0002_persona_fk_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fk_cliente',
        ),
    ]
