# Generated by Django 3.1.3 on 2020-11-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0003_remove_persona_fk_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Persona',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Contactos.persona'),
            preserve_default=False,
        ),
    ]
