# Generated by Django 3.1.3 on 2020-11-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0004_cliente_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Telefono',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Contactos.telefonocliente'),
            preserve_default=False,
        ),
    ]
