# Generated by Django 3.1.3 on 2020-11-09 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0005_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonocliente',
            name='Tipo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Contactos.tipotelefono'),
            preserve_default=False,
        ),
    ]
