# Generated by Django 3.1.3 on 2020-11-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0006_telefonocliente_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Telefono',
        ),
        migrations.AlterField(
            model_name='telefonocliente',
            name='predeterminado',
            field=models.BooleanField(verbose_name='Predeterminado'),
        ),
    ]
