# Generated by Django 3.1.3 on 2020-11-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0008_telefonocliente_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefonocliente',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='telefonocliente',
            name='Cliente',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Contactos.cliente'),
            preserve_default=False,
        ),
    ]
